#!/usr/bin/env python3
import sys, subprocess

args = sys.argv
strArgs = ''
args[0] = "git"
for arg in args:
    if " " in arg:
        arg = '\"%s\"' % arg
    strArgs += '%s ' % arg

try:
    out = subprocess.call(strArgs, shell=True)
except subprocess.CalledProcessError as e:
    pass # do nothing as error is displayed as part of the git command
