#!/usr/bin/env python3
import sys, subprocess

args = sys.argv
strArgs = ''
args[0] = "git"
for arg in args:
    if " " in arg:
        arg = '\"%s\"' % arg
    strArgs += '%s ' % arg

try:
    out = subprocess.run(strArgs, check=True, stderr=subprocess.PIPE, shell=True)
except subprocess.CalledProcessError as e:
    err = e.stderr.decode("ascii")
    print(err)
